services:
  observer:
    image: ghcr.io/danielpower/osu-observer:latest
    ports:
      - "80:80"
    env_file: .env
    environment:
      - SAVE_MEDIA_PATH=/data/media
    volumes:
      - media:/data/media

volumes:
  media:
